apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluentbit
  namespace: fluentbit
spec:
  interval: 1m
  chart:
    spec:
      chart: fluent-bit
      version: "0.19.17"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: fluentbit