apiVersion: v1
kind: Secret
metadata:
  name: azure-monitor
  namespace: fluentbit
data:
  # Replace value with your Base64 encoded Azure Log Analytics workspace id
  customer_id: d29ya3NwYWNlaWQ=
  # Replace value with your Base64 encoded Azure Log Analytics primary or secondary key
  shared_key: c2hhcmVkX2tleQ==