apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{app}}-ingress
  namespace: {{app}}
spec:
  rules:
  - host: {{fqdn}}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{app}}
            port:
              number: {{port}}
