apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{app}}-ingress
  namespace: {{app}}
spec:
  ingressClassName: contour
  defaultBackend:
    service:
      name: default-http-backend
      port:
        number: 80
        