apiVersion: v1
kind: Service
metadata:
  name: {{app}}
  namespace: {{app}}
spec:
  selector:
    app: {{app}}
  ports:
    - protocol: TCP
      port: {{port}}
      targetPort: {{port}}
