kind: ApplicationDeployment
metadata:
  # Name of the application. Must be unique within a workspace.
  name: myapp
spec:
  # Name of the workspace to which the application belongs
  workspace: workspace1

  # The Git repository, ref (branch, tag, or commit sha), and relative path used to access the application's app.yaml
  app:
    repo: https://github.com/myuser/myapp
    ref: main
    path: app.yaml

  # Targets describe how and where an application should be deployed
  targets:
    # Target keys are arbitrary names used for organization and must be unique within an ApplicationDeployment
    us-dev:
      # Only clusters with labels/environments that match the defined selector will be eligible for assignment
      # If selector is empty or not present, the deployment is eligible for assignment to any cluster
      selector:
        cloud: azure
        geo: us
        environment: dev

      # The number of clusters to deploy to, or the string 'all' to deploy to all that match the selector
      clusters: 1

    # Example of a second deployment with an alternate set of values
    us-staging:
      selector:
        cloud: azure
        geo: us
        environment: staging
      clusters: 1

      # (Optional) The reference to app.yaml can be set on a per-target basis
      app:
        path: app.staging.yaml

      # (Optional) The Platform Team can also override app.yaml values with the values here
      values:
        replicas: 1
        memory: 512M
