apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluentbit
  namespace: fluentbit
spec:
  values:
    env: 
    - name: "LOG_ANALYTICS_WORKSPACE_ID"
      valueFrom:
        secretKeyRef:
          key:  workspace_id
          name: azure-log-analytics
    - name: "LOG_ANALYTICS_KEY"
      valueFrom:
        secretKeyRef:
          key:  key
          name: azure-log-analytics    
    config:
      inputs: |
        [INPUT]
            Name        tcp
            Tag         prometheus
            Listen      0.0.0.0
            Port        5170

        [INPUT]
            Name tail
            Path /var/log/containers/*.log
            parser cri
            Tag kube.*
            Mem_Buf_Limit 5MB
            Skip_Long_Lines On
            Refresh_Interval  10    
            
      outputs: |
        [OUTPUT]
            Name            azure
            Match           kube.*
            Log_Type        clusterlogs
            Customer_ID     ${LOG_ANALYTICS_WORKSPACE_ID}
            Shared_Key      ${LOG_ANALYTICS_KEY}
            time_generated  true

        [OUTPUT]
            Name            azure
            Match           prometheus
            Log_Type        clustermetrics
            Customer_ID     ${LOG_ANALYTICS_WORKSPACE_ID}
            Shared_Key      ${LOG_ANALYTICS_KEY}
            time_generated  true 