apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: {{coral.app}}
  namespace: flux-system
  labels:
  {{#coral.labels}}
    {{key}}: {{value}}
  {{/coral.labels}}
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: {{coral.app}}
  path: {{folder}}
  prune: true
  validation: client  