kind: ZarfPackageConfig
metadata:
  name: {{coral.app}}
components:
  - name: {{coral.app}}
    required: true
    manifests:
      - name: rancher-hello-world
        kustomizations:
          - {{repository}}//{{folder}}/?ref={{branch}}
    images:
      - {{zarf_image}}