apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{coral.app}}-deployment
  namespace: {{coral.workspace}}-{{coral.app}}-{{coral.deployment}}
  labels:
  {{#coral.labels}}
    {{key}}: {{value}}
  {{/coral.labels}}
spec:
  replicas: {{replicas}}
  selector:
    matchLabels:
      app: {{coral.app}}
  template:
    metadata:
      labels:
        {{#coral.labels}}
        {{key}}: {{value}}
        {{/coral.labels}}
    spec:
      containers:
      - name: {{coral.app}}
        image: {{image}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{port}}
