apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{coral.app}}-ingress
  namespace: {{coral.workspace}}-{{coral.app}}-{{coral.deployment}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{coral.app}}
            port:
              number: 8000