kind: ApplicationDeployment
metadata:
  name: <app-name> # REQUIRED: unique name of application
spec:
  workspace: <workspace-name> # REQUIRED: assigned workspace
  app:
    repo: <repo-URL>  # REQUIRED: The url to a Git repository where the Application (app.yaml) is located
    ref: <git-reference>  # REQUIRED: The Git ref (branch/tag/commit) to use
    path: <app-yaml-path>  # REQUIRED: The path within the repo to the Application (app.yaml) file
  targets:
    <target-name>: # REQUIRED: target name, examples: dev, prod, staging-westus, prod-southcentralus, etc.
      app:  # we can override values from the main spec for an specific target
        repo: <repo-URL>
        ref: <git-reference>
        path: <app-yaml-path>
      clusters: <number-of-clusters-needed> # REQUIRED: The number of clusters to deploy to, or 'all' for all clusters that match the selector
      selector:
        # Create assignments on clusters with label keys and values matching this selector. 
        # If empty or not present, the deployment is assumed to target any registered Cluster
        environment: <environment>
        geo: <geo>
      values: 
        # Template values to be set during deployment.
        # Map of string keys and values that can be used to override template defaults and app values
        replicas: <number-of-replicas> # Examples of possible values
        memory: <amount-of-memory>
    